### PR TITLE
Added unique constraint creator

### PR DESCRIPTION
**Pull request by rabbiveesh**
First of all, I love this dist. It really does make writing DDL as easy as it is in SQL.

I added a shortcut for creating unique constraints.

### CODE REVIEW

**Comment by nrdvana** [comment]
Hi, glad to hear it's useful :-)    The new keyword is good, though new keywords can't go into existing tags.  It would need to be a "V2" that introduces this symbol.  I can make the change, or you can, either way.

**Comment by rabbiveesh** [comment]
Sorry, didn't realize how commited you were to a stable API.

Question: do you think we could mark off the next version as experimental,
so it could contain more than just this one tag?

**Comment by nrdvana** [comment]
Sure.  Do you have some other ideas to add?  It can also be an exportable symbol without belonging to any tags - you would just import it as

  use DBIx::Class::ResultDDL -V1, 'unique';

I also don't mind running through lots of tag numbers.  Right now each one is a new function, but if the collection gets larger I can write a dynamic generator.

**Comment by rabbiveesh** [comment]
I don't have any more ideas yet, but as they come up, I'll pull more
requests.
I also want to make a documentation change, because it took me a little bit
to get the whole relationships the other way around example. I'll push what
I'm thinking of.

**Pull request merged**
