### PR TITLE
begin implementing views

### PR DESCRIPTION
**Pull request by rabbiveesh**
I implemented a 'view' function, which will allow you to create a view in one statement.

It takes the following arguments
```perl
   view $table_name, $table_definition, %options;
```
where options takes the keys `is_virtual` to toggle whether or not it's a virtual view, and `depends` which takes an arrayref of tables that this view's deployment is dependant on.

### CODE REVIEW

**Comment by nrdvana** [comment]
Looks good.  Did you want to add the tests first?  and I assume you'd like to add it to the default imports for the next version?

**Comment by rabbiveesh** [comment]
yeah, lemme add tests. When are you planning on releasing to CPAN, by the
way?

**Comment by nrdvana** [comment]
Just whenever the feature set looks good.  I was planning to add all the type names used by Postgres at some point.

**Comment by rabbiveesh** [comment]
Hey, sorry for the forever delay. I've got the test implemented now @nrdvana . I added the CommitBuild dzil plugin b/c I've been using this in production, and was installing off of github.

**Pull request merged**
